FROM python:3.9-alpine3.13
LABEL maintainer="masamichan.com"

ENV PYTHONBUFFER 1

COPY ./requirements.txt /tmp/requirements.txt
COPY ./app /app
WORKDIR /app 
EXPOSE 8000

RUN python -m venv /py && \
  /py/bin/pip install --upgrade pip && \
  rm -rf /tmp && \
  aduser \
  --disabled-password \
  --no-create-home \
  django-user

ENV path="/py/bin:$PATH"

USER django-user
